[package]
name = "mother_board"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codespan-reporting = "0.11.1"
g-code = "0.3.4"
mio-serial = "5.0.5"
