[package]
name = "mother_board"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = {version = "4.2.0", default-features = false}
tokio = { version = "1.28.1", features = ["full"]}